### ISSUE TITLE
How to convert a .sb3 to .html in the command line?

### ISSUE THREAD

**Issue by NonlinearFruit** [TurboWarp/packager#556]
I have a repo with scratch files (sb3) and I'd love to have my pipeline convert them to html and host them via github/gitlab pages.

Can I use this repo to do that? Is there some documentation?

I'm looking for something like
```
npm convert --to-html file.sb3 --output public/file.html
```

**Comment by NonlinearFruit** [comment]
Would this be the best way to do it? (I just found this demo script)

- Use a js script
- Add `@turbowarp/packager` dependency
- Load the sb3 into memory
- Pass to the library
- Have the library output html
- Write the result to `public/html`

https://github.com/TurboWarp/packager/blob/master/node-api-docs/demo.js

**Comment by GarboMuffin** [comment]
Yes, that's probably the best solution. You can ask here if you have trouble doing that.

**Comment by GarboMuffin** [comment]
If you didn't already see, https://github.com/TurboWarp/packager/tree/master/node-api-docs#readme explains in more detail what's going on in that file, and other things that you might care about

**Comment by NonlinearFruit** [comment]
I'm getting a 'n is not a function' error when trying to package even the simplest project
```
TypeError: n is not a function
    at Object.onProgress (/mnt/c/Users/<user>/Projects/Scratch/node_modules/@turbowarp/packager/dist/packager.js:1:55697)
    at /mnt/c/Users/<user>/Projects/Scratch/node_modules/@turbowarp/sbdl/lib/bundle-node.cjs:548:15
    at StreamHelper.<anonymous> (/mnt/c/Users/<user>/Projects/Scratch/node_modules/jszip/lib/stream/StreamHelper.js:89:21)
    at ConvertWorker.<anonymous> (/mnt/c/Users/<user>/Projects/Scratch/node_modules/jszip/lib/stream/StreamHelper.js:167:20)
    at ConvertWorker.emit (/mnt/c/Users/<user>/Projects/Scratch/node_modules/jszip/lib/stream/GenericWorker.js:122:42)
    at ConvertWorker.push (/mnt/c/Users/<user>/Projects/Scratch/node_modules/jszip/lib/stream/GenericWorker.js:48:14)
    at ConvertWorker.processChunk (/mnt/c/Users/<user>/Projects/Scratch/node_modules/jszip/lib/stream/ConvertWorker.js:21:10)
    at ZipFileWorker.<anonymous> (/mnt/c/Users/<user>/Projects/Scratch/node_modules/jszip/lib/stream/GenericWorker.js:154:18)
    at ZipFileWorker.emit (/mnt/c/Users/<user>/Projects/Scratch/node_modules/jszip/lib/stream/GenericWorker.js:122:42)
    at ZipFileWorker.push (/mnt/c/Users/<user>/Projects/Scratch/node_modules/jszip/lib/stream/GenericWorker.js:48:14)
```

Code is this with `"@turbowarp/packager": "1.3.0"`
```js
const fs = require('fs')
const path = require('path')
const packager = require('@turbowarp/packager')

const run = async () => {
  const projectFile = process.argv[2];
  console.log("Project File: "+projectFile);
  const projectData = fs.readFileSync(projectFile, 'binary');
  const loadedProject = await packager.loadProject(projectData);

  //const packager = new packager.Packager();
  //packager.project = loadedProject;

  //const result = await packager.package();
  //fs.writeFileSync(path.join(__dirname, 'demo_output.html'), result.data);
};

run()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
```

Originally, I was using one of my projects. But I'm also getting this error when using an almost blank project (start empty scratch, export to file). I've attached my blank project here (I needed to add the `.zip` extension to attach it). I did verify that the project data was being read in as binary

[sample_project.sb3.zip](https://github.com/TurboWarp/packager/files/9788491/sample_project.sb3.zip)

**Comment by GarboMuffin** [comment]
you should do this instead:

```js
  const projectData = fs.readFileSync(projectFile);
  const progressCallback = () => {};
  const loadedProject = await packager.loadProject(projectData, progressCallback);
```

loadProject has a second argument that's a function it'll call with progress information. It's supposed to be optional but apparently that was broken at some point

**Comment by GarboMuffin** [comment]
Here's a more complete fixed version with `Packager` vs `packager` also fixed

```js
const fs = require('fs')
const path = require('path')
const Packager = require('@turbowarp/packager')

const run = async () => {
  const projectFile = process.argv[2];
  console.log("Project File: "+projectFile);
  const projectData = fs.readFileSync(projectFile);
  const progressCallback = () => {};
  const loadedProject = await Packager.loadProject(projectData, progressCallback);

  const packager = new Packager.Packager();
  packager.project = loadedProject;

  const result = await packager.package();
  fs.writeFileSync(path.join(__dirname, 'demo_output.html'), result.data);
};

run()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
```

**Comment by NonlinearFruit** [comment]
Thanks! That did the trick. Super slick 🥇


In case anyone else is interested (#96), this is how I set it up for GitLab pages. I'll fiddle with my solution some more after #557 😁 

`index.js`
```js
const fs = require('fs')
const path = require('path')
const Packager = require('@turbowarp/packager')

const run = async () => {
  const projectData = loadProjectData();
  const html = await compileProjectToHtml(projectData);
  outputHtml(html);
};

function loadProjectData() {
  const projectFile = process.argv[2];
  return fs.readFileSync(projectFile, 'binary');
}

async function compileProjectToHtml(projectData) {
  const progressCallback = (type, a, b) => { };
  const loadedProject = await Packager.loadProject(projectData, progressCallback);

  const packager = new Packager.Packager();
  packager.project = loadedProject;

  const result = await packager.package();
  return result.data;
}

function outputHtml(html) {
  console.log(html);
}

run()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
```

`.gitlab-ci.yml`
```yml
pages:
  image: node:lts-alpine
  script:
    - npm install
    - mkdir public
    - for file in *.sb3; do node index.js $file > public/$(echo $file | sed 's/sb3/html/'); done
  artifacts:
    paths:
    - public
```
